# Loading Data Using Pandas

Before performing any data cleaning or analysis, we'll need to load our specimen data - in this case, it's stored in a CSV file.

First, we'll import pandas:

In [2]:
import pandas as pd

Then we'll tell pandas to read our CSV file, creating a [dataframe](https://pandas.pydata.org/docs/user_guide/10min.html#basic-data-structures-in-pandas)

The second line - where we just have the name of our dataframe - tells Python to evaluate (show) the dataframe we just created!

In [3]:
specimen_df = pd.read_csv("../data/specimens.csv")
specimen_df

,specimen_id,visit_id,patient_id,site_id,study_id,specimen_type,aliquot_number
0,VISIT00000_HEPARIN_PLASMA_01,VISIT00000,PT0007,SITE000,1,Heparin plasma,1
1,VISIT00000_HEPARIN_PLASMA_02,VISIT00000,PT0007,SITE000,1,Heparin plasma,2
2,VISIT00000_PAXGENE_RNA_01,VISIT00000,PT0007,SITE000,1,PAXgene RNA,1
3,VISIT00000_PAXGENE_RNA_02,VISIT00000,PT0007,SITE000,1,PAXgene RNA,2
4,VISIT00000_PAXGENE_RNA_03,VISIT00000,PT0007,SITE000,1,PAXgene RNA,3
5,VISIT00000_PAXGENE_RNA_04,VISIT00000,PT0007,SITE000,1,PAXgene RNA,4
6,VISIT00001_EDTA_PLASMA_01,VISIT00001,PT0003,SITE002,1,EDTA plasma,1
7,VISIT00001_EDTA_PLASMA_02,VISIT00001,PT0003,SITE002,1,EDTA plasma,2
8,VISIT00001_EDTA_PLASMA_03,VISIT00001,PT0003,SITE002,1,EDTA plasma,3
9,VISIT00001_EDTA_PLASMA_04,VISIT00001,PT0003,SITE002,1,EDTA plasma,4
10,VISIT00001_EDTA_PLASMA_05,VISIT00001,PT0003,SITE002,1,EDTA plasma,5
11,VISIT00001_EDTA_PLASMA_06,VISIT00001,PT0003,SITE002,1,EDTA plasma,6
12,VISIT00001_HEPARIN_PLASMA_01,VISIT00001,PT0003,SITE002,1,Heparin plasma,1
13,VISIT00001_HEPARIN_PLASMA_02,VISIT00001,PT0003,SITE002,1,Heparin plasma,2
14,VISIT00001_HEPARIN_PLASMA_03,VISIT00001,PT0003,SITE002,1,Heparin plasma,3
15,VISIT00001_HEPARIN_PLASMA_04,VISIT00001,PT0003,SITE002,1,Heparin plasma,4
16,VISIT00001_HEPARIN_PLASMA_05,VISIT00001,PT0003,SITE002,1,Heparin plasma,5
17,VISIT00001_HEPARIN_PLASMA_06,VISIT00001,PT0003,SITE002,1,Heparin plasma,6
18,VISIT00001_PAXGENE_RNA_01,VISIT00001,PT0003,SITE002,1,PAXgene RNA,1
19,VISIT00001_PAXGENE_RNA_02,VISIT00001,PT0003,SITE002,1,PAXgene RNA,2
20,VISIT00001_PAXGENE_RNA_03,VISIT00001,PT0003,SITE002,1,PAXgene RNA,3
21,VISIT00002_EDTA_PLASMA_01,VISIT00002,PT0009,SITE000,1,EDTA plasma,1
22,VISIT00002_EDTA_PLASMA_02,VISIT00002,PT0009,SITE000,1,EDTA plasma,2
23,VISIT00002_EDTA_PLASMA_03,VISIT00002,PT0009,SITE000,1,EDTA plasma,3
24,VISIT00002_PAXGENE_RNA_01,VISIT00002,PT0009,SITE000,1,PAXgene RNA,1
25,VISIT00002_PAXGENE_RNA_02,VISIT00002,PT0009,SITE000,1,PAXgene RNA,2
26,VISIT00002_PAXGENE_RNA_03,VISIT00002,PT0009,SITE000,1,PAXgene RNA,3
27,VISIT00003_EDTA_PLASMA_01,VISIT00003,PT0004,SITE002,1,EDTA plasma,1
28,VISIT00003_EDTA_PLASMA_02,VISIT00003,PT0004,SITE002,1,EDTA plasma,2
29,VISIT00003_EDTA_PLASMA_03,VISIT00003,PT0004,SITE002,1,EDTA plasma,3
30,VISIT00003_EDTA_PLASMA_04,VISIT00003,PT0004,SITE002,1,EDTA plasma,4
31,VISIT00003_EDTA_PLASMA_05,VISIT00003,PT0004,SITE002,1,EDTA plasma,5
32,VISIT00003_EDTA_PLASMA_06,VISIT00003,PT0004,SITE002,1,EDTA plasma,6
33,VISIT00003_HEPARIN_PLASMA_01,VISIT00003,PT0004,SITE002,1,Heparin plasma,1
34,VISIT00003_PAXGENE_RNA_01,VISIT00003,PT0004,SITE002,1,PAXgene RNA,1
35,VISIT00003_PAXGENE_RNA_02,VISIT00003,PT0004,SITE002,1,PAXgene RNA,2
36,VISIT00003_PAXGENE_RNA_03,VISIT00003,PT0004,SITE002,1,PAXgene RNA,3
37,VISIT00003_SERUM_01,VISIT00003,PT0004,SITE002,1,Serum,1
38,VISIT00003_SERUM_02,VISIT00003,PT0004,SITE002,1,Serum,2
39,VISIT00003_SERUM_03,VISIT00003,PT0004,SITE002,1,Serum,3
40,VISIT00003_SERUM_04,VISIT00003,PT0004,SITE002,1,Serum,4
41,VISIT00003_SERUM_05,VISIT00003,PT0004,SITE002,1,Serum,5
42,VISIT00004_EDTA_PLASMA_01,VISIT00004,PT0006,SITE000,1,EDTA plasma,1
43,VISIT00004_EDTA_PLASMA_02,VISIT00004,PT0006,SITE000,1,EDTA plasma,2
44,VISIT00004_HEPARIN_PLASMA_01,VISIT00004,PT0006,SITE000,1,Heparin plasma,1
45,VISIT00004_HEPARIN_PLASMA_02,VISIT00004,PT0006,SITE000,1,Heparin plasma,2
46,VISIT00004_HEPARIN_PLASMA_03,VISIT00004,PT0006,SITE000,1,Heparin plasma,3
47,VISIT00004_PAXGENE_RNA_01,VISIT00004,PT0006,SITE000,1,PAXgene RNA,1
48,VISIT00004_PAXGENE_RNA_02,VISIT00004,PT0006,SITE000,1,PAXgene RNA,2
49,VISIT00004_PAXGENE_RNA_03,VISIT00004,PT0006,SITE000,1,PAXgene RNA,3
50,VISIT00004_PAXGENE_RNA_04,VISIT00004,PT0006,SITE000,1,PAXgene RNA,4
51,VISIT00004_PAXGENE_RNA_05,VISIT00004,PT0006,SITE000,1,PAXgene RNA,5

Looks good - but for this task, we'll only need _plasma_ specimens.

To do that, we'll create a new dataframe that filters for the phrase "plasma" in the `specimen_type` column (using pandas' [boolean indexing](https://pandas.pydata.org/docs/user_guide/10min.html#boolean-indexing))

In [4]:
plasma_df = specimen_df[specimen_df['specimen_type'].str.contains('plasma')]
plasma_df

,specimen_id,visit_id,patient_id,site_id,study_id,specimen_type,aliquot_number
0,VISIT00000_HEPARIN_PLASMA_01,VISIT00000,PT0007,SITE000,1,Heparin plasma,1
1,VISIT00000_HEPARIN_PLASMA_02,VISIT00000,PT0007,SITE000,1,Heparin plasma,2
6,VISIT00001_EDTA_PLASMA_01,VISIT00001,PT0003,SITE002,1,EDTA plasma,1
7,VISIT00001_EDTA_PLASMA_02,VISIT00001,PT0003,SITE002,1,EDTA plasma,2
8,VISIT00001_EDTA_PLASMA_03,VISIT00001,PT0003,SITE002,1,EDTA plasma,3
9,VISIT00001_EDTA_PLASMA_04,VISIT00001,PT0003,SITE002,1,EDTA plasma,4
10,VISIT00001_EDTA_PLASMA_05,VISIT00001,PT0003,SITE002,1,EDTA plasma,5
11,VISIT00001_EDTA_PLASMA_06,VISIT00001,PT0003,SITE002,1,EDTA plasma,6
12,VISIT00001_HEPARIN_PLASMA_01,VISIT00001,PT0003,SITE002,1,Heparin plasma,1
13,VISIT00001_HEPARIN_PLASMA_02,VISIT00001,PT0003,SITE002,1,Heparin plasma,2
14,VISIT00001_HEPARIN_PLASMA_03,VISIT00001,PT0003,SITE002,1,Heparin plasma,3
15,VISIT00001_HEPARIN_PLASMA_04,VISIT00001,PT0003,SITE002,1,Heparin plasma,4
16,VISIT00001_HEPARIN_PLASMA_05,VISIT00001,PT0003,SITE002,1,Heparin plasma,5
17,VISIT00001_HEPARIN_PLASMA_06,VISIT00001,PT0003,SITE002,1,Heparin plasma,6
21,VISIT00002_EDTA_PLASMA_01,VISIT00002,PT0009,SITE000,1,EDTA plasma,1
22,VISIT00002_EDTA_PLASMA_02,VISIT00002,PT0009,SITE000,1,EDTA plasma,2
23,VISIT00002_EDTA_PLASMA_03,VISIT00002,PT0009,SITE000,1,EDTA plasma,3
27,VISIT00003_EDTA_PLASMA_01,VISIT00003,PT0004,SITE002,1,EDTA plasma,1
28,VISIT00003_EDTA_PLASMA_02,VISIT00003,PT0004,SITE002,1,EDTA plasma,2
29,VISIT00003_EDTA_PLASMA_03,VISIT00003,PT0004,SITE002,1,EDTA plasma,3
30,VISIT00003_EDTA_PLASMA_04,VISIT00003,PT0004,SITE002,1,EDTA plasma,4
31,VISIT00003_EDTA_PLASMA_05,VISIT00003,PT0004,SITE002,1,EDTA plasma,5
32,VISIT00003_EDTA_PLASMA_06,VISIT00003,PT0004,SITE002,1,EDTA plasma,6
33,VISIT00003_HEPARIN_PLASMA_01,VISIT00003,PT0004,SITE002,1,Heparin plasma,1
42,VISIT00004_EDTA_PLASMA_01,VISIT00004,PT0006,SITE000,1,EDTA plasma,1
43,VISIT00004_EDTA_PLASMA_02,VISIT00004,PT0006,SITE000,1,EDTA plasma,2
44,VISIT00004_HEPARIN_PLASMA_01,VISIT00004,PT0006,SITE000,1,Heparin plasma,1
45,VISIT00004_HEPARIN_PLASMA_02,VISIT00004,PT0006,SITE000,1,Heparin plasma,2
46,VISIT00004_HEPARIN_PLASMA_03,VISIT00004,PT0006,SITE000,1,Heparin plasma,3

That looks better - but we've still got two different preservatives (Heparin and EDTA).

If we want only EDTA plasma, we can use boolean indexing/filtering again to get only _EDTA plasma_ specimens:

In [5]:
edta_plasma_df = plasma_df[plasma_df['specimen_type'].str.contains('EDTA')]
edta_plasma_df

,specimen_id,visit_id,patient_id,site_id,study_id,specimen_type,aliquot_number
6,VISIT00001_EDTA_PLASMA_01,VISIT00001,PT0003,SITE002,1,EDTA plasma,1
7,VISIT00001_EDTA_PLASMA_02,VISIT00001,PT0003,SITE002,1,EDTA plasma,2
8,VISIT00001_EDTA_PLASMA_03,VISIT00001,PT0003,SITE002,1,EDTA plasma,3
9,VISIT00001_EDTA_PLASMA_04,VISIT00001,PT0003,SITE002,1,EDTA plasma,4
10,VISIT00001_EDTA_PLASMA_05,VISIT00001,PT0003,SITE002,1,EDTA plasma,5
11,VISIT00001_EDTA_PLASMA_06,VISIT00001,PT0003,SITE002,1,EDTA plasma,6
21,VISIT00002_EDTA_PLASMA_01,VISIT00002,PT0009,SITE000,1,EDTA plasma,1
22,VISIT00002_EDTA_PLASMA_02,VISIT00002,PT0009,SITE000,1,EDTA plasma,2
23,VISIT00002_EDTA_PLASMA_03,VISIT00002,PT0009,SITE000,1,EDTA plasma,3
27,VISIT00003_EDTA_PLASMA_01,VISIT00003,PT0004,SITE002,1,EDTA plasma,1
28,VISIT00003_EDTA_PLASMA_02,VISIT00003,PT0004,SITE002,1,EDTA plasma,2
29,VISIT00003_EDTA_PLASMA_03,VISIT00003,PT0004,SITE002,1,EDTA plasma,3
30,VISIT00003_EDTA_PLASMA_04,VISIT00003,PT0004,SITE002,1,EDTA plasma,4
31,VISIT00003_EDTA_PLASMA_05,VISIT00003,PT0004,SITE002,1,EDTA plasma,5
32,VISIT00003_EDTA_PLASMA_06,VISIT00003,PT0004,SITE002,1,EDTA plasma,6
42,VISIT00004_EDTA_PLASMA_01,VISIT00004,PT0006,SITE000,1,EDTA plasma,1
43,VISIT00004_EDTA_PLASMA_02,VISIT00004,PT0006,SITE000,1,EDTA plasma,2

Finally, we often have to use a particular aliquot (or "sequence") number - for instance, if we're only allowed to work with EDTA aliquot #2, we can filter even further on the `aliquot_number` column to get just sequence 2:

In [6]:
edta_plasma_seq1 = edta_plasma_df[edta_plasma_df['aliquot_number'].eq(2)]
edta_plasma_seq1

,specimen_id,visit_id,patient_id,site_id,study_id,specimen_type,aliquot_number
7,VISIT00001_EDTA_PLASMA_02,VISIT00001,PT0003,SITE002,1,EDTA plasma,2
22,VISIT00002_EDTA_PLASMA_02,VISIT00002,PT0009,SITE000,1,EDTA plasma,2
28,VISIT00003_EDTA_PLASMA_02,VISIT00003,PT0004,SITE002,1,EDTA plasma,2
43,VISIT00004_EDTA_PLASMA_02,VISIT00004,PT0006,SITE000,1,EDTA plasma,2